# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NeroEdu' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'MediaPipeTasksGenAI'
  pod 'MediaPipeTasksGenAIC'
  # Pods for NeroEdu

end
